name: gitleaks

on:
  push:
    branches: 
       - Master
       - Staging
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ Master ]
  schedule:
    - cron: '15 8 * * 0'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
