# Base on https://github.com/marketplace/actions/build-and-push-docker-images

name: Docker push and deploy 

on:
  push:
    branches:
      - 'Master'

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1	
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1	
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}		
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tr4nt0/web-example-golang:latest
  Deploy-container:
    needs: Docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app on docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: ${{ secrets.VM_PORT }}
          script: |
            docker rm -f web-example-golang && docker rmi -f tr4nt0/web-example-golang:latest
            docker-compose -f ${{ secrets.VM_DIRECTORY }}/docker-compose.yml up -d
